application: battleship
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: api.api

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

libraries:
- name: endpoints
  version: 1.0
